Repository AthenZ/k8s-athenz-sia, pull requests merged in 2023-11, with the labels that each got.

#52 Fix Instance Cert Bug (Hotfix branch)
  cmd/athenz-sia/main.go
  pkg/identity/certificated.go
Labels: bug

#56 Snyk vulnerability handle for future SIA v3.1.2
  go.mod
  go.sum
Labels: dependencies

#53 Fix Instance Cert Bug
  athenz-sia.env
  pkg/config/config.go
  pkg/identity/certificated.go
Labels: bug

#48 Update athenz-sia.env ROLE_CERT_KEY_FILE_OUTPUT
  athenz-sia.env
Labels: documentation

#62 Fix So That SIA does NOT Write Instance Cert When Local File Backup Used
  pkg/identity/certificated.go
Labels: bug
