Repository AthenZ/k8s-athenz-sia, pull requests merged in 2024-09, with the labels that each got.

#131 Writing Token Files Update Individually with Go Routine
  pkg/token/cache.go
  pkg/token/server.go
  pkg/token/service.go
Labels: enhancement

#138 Fix Save Token Log
  pkg/token/service.go
Labels: logging

#136 Get token by specifying only the domain in TARGET_DOMAIN_ROLES
  pkg/certificate/identity.go
  pkg/certificate/service.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/model.go
  pkg/metrics/service.go
  pkg/token/service.go
Labels: enhancement

#141 Add Path Generator
  pkg/util/path-generator.go
  pkg/util/path-generator_test.go
Labels: enhancement

#142 Add directory creator
  pkg/certificate/service.go
  pkg/token/service.go
  pkg/util/directory-creator.go
Labels: refactor

#145 Role cert with derived state and its new config
  pkg/certificate/identity.go
  pkg/certificate/service.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/derived-access-token.go
  pkg/config/derived-role-cert.go
  pkg/config/dervied.go
  pkg/config/model.go
  pkg/metrics/service.go
Labels: refactor

#146 Fix Derived RoleCert Dir
  pkg/config/derived-role-cert.go
Labels: bug

#147 Refactor parseTargetDomainRoles with derived state `DerivedRoleCert`
  pkg/config/config.go
  pkg/config/derived-role-cert.go
  pkg/config/derived-target-domain-roles.go
  pkg/config/dervied.go
  pkg/config/model.go
Labels: refactor

#148 Refactor derived-role-cert with `Format` & `KeyFormat`
  pkg/certificate/service.go
  pkg/config/derived-role-cert.go
  pkg/metrics/service.go
Labels: refactor

#152 Refactor Backup Related State
  pkg/certificate/identity.go
  pkg/certificate/service.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/derived-k8s-secret-backup.go
  pkg/config/dervied.go
  pkg/config/model.go
Labels: refactor

#149 Feat/role cert naming format
  athenz-sia.env
  pkg/certificate/identity.go
  pkg/certificate/service.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/derived-role-cert.go
  pkg/config/dervied.go
  pkg/config/model.go
Labels: enhancement, logging

#159 Remove unnecessary configurations for the TokenServer from service.go
  pkg/token/server.go
  pkg/token/service.go
Labels: refactor

#160 Refactor: TokenFile with DerivedState
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/derived-access-token.go
  pkg/config/derived-target-domain-roles.go
  pkg/config/derived-token-file.go
  pkg/config/dervied.go
  pkg/config/model.go
  pkg/token/service.go
Labels: refactor

#161 Refactor: TokenServer with DerivedState
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/derived-token-server.go
  pkg/config/dervied.go
  pkg/config/model.go
  pkg/token/server.go
  pkg/token/service.go
Labels: refactor

#162 Refactor derived-token-file with `Format`
  pkg/config/derived-token-file.go
  pkg/token/service.go
Labels: refactor

#156 Terminate if file output fails in init mode
  pkg/token/service.go
Labels: enhancement

#163 Feat/token naming format
  Makefile
  athenz-sia.env
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/derived-token-file.go
  pkg/config/model.go
  pkg/token/service.go
Labels: enhancement
