Repository AthenZ/k8s-athenz-sia, pull requests merged in 2024-02, with the labels that each got.

#75 Update token cache logic
  .licenserc.yaml
  pkg/token/daemon.go
Labels: bug

#77 Add token expiry metrics
  go.sum
  pkg/token/cache.go
  pkg/token/daemon.go
Labels: enhancement

#76 Support RSA #pkcs8 private key
  go.mod
  go.sum
  pkg/identity/identity.go
Labels: enhancement

#78 Add enable Envoy API option
  athenz-sia.env
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/model.go
  pkg/token/daemon.go
  pkg/token/server.go
Labels: enhancement

#81 Fix Env TOKEN_SERVER_ENVOY_API -> USE_TOKEN_SERVER
  athenz-sia.env
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/model.go
  pkg/token/daemon.go
  pkg/token/server.go
Labels: enhancement

#83 Improve logger for token server
  go.mod
  pkg/identity/healthcheckd.go
  pkg/token/server.go
Labels: logging
