Repository AthenZ/k8s-athenz-sia, pull requests merged in 2024-03, with the labels that each got.

#88 Add build_info log and metrics
  cmd/athenz-sia/main.go
Labels: enhancement

#89 Golang Singleflight for fetching at/rt to zts server
  go.mod
  go.sum
  pkg/token/cache.go
  pkg/token/daemon.go
  pkg/token/server.go
  pkg/token/type.go
Labels: enhancement, logging

#97 Disable maxExpiry Option When obtaining a role token
  pkg/token/athenz.go
  pkg/token/server.go
Labels: enhancement

#103 token metrics with k8s namespace and k8s pod name
  athenz-sia.env
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/model.go
  pkg/token/cache.go
  pkg/token/daemon.go
Labels: enhancement

#100 revamp startup and shutdown flow
  cmd/athenz-sia/main.go
  docs/development/sia-goroutine-and-channel.md
  go.mod
  go.sum
  pkg/certificate/identity.go
  pkg/certificate/service.go
  pkg/config/default.go
  pkg/daemon/daemon.go
  pkg/daemon/httpchecker.go
  pkg/healthcheck/service.go
  pkg/k8s/secret.go
  pkg/metrics
  pkg/metrics/gauge.go
  pkg/metrics/internal
  pkg/metrics/service.go
  pkg/token/cache.go
  pkg/token/daemon.go
  pkg/token/server.go
  pkg/token/service.go
Labels: enhancement

#108 Unify variable name as `idCfg` and create `USER_AGENT` constant
  Makefile
  cmd/athenz-sia/main.go
  pkg/certificate/identity.go
  pkg/certificate/service.go
  pkg/config/config.go
  pkg/config/runtime-constant.go
  pkg/daemon/daemon.go
  pkg/healthcheck/service.go
  pkg/metrics/service.go
  pkg/token/athenz.go
  pkg/token/service.go
Labels: refactor

#112 Log not accurate enough
  pkg/token/service.go
Labels: logging

#114 Update pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#118 Fix condition for `r.pollRefresh()`
  pkg/util/tls-reload.go
Labels: bug

#111 fix certreloader update logic
  pkg/certificate/service.go
Labels: bug

#116 fix development doc
  docs/development/mode=refresh-sequence.md
Labels: documentation
