Repository AthenZ/k8s-athenz-sia, pull requests merged in 2024-04, with the labels that each got.

#121 Fix Vulnerability SNYK-GOLANG-GOLANGORGXNETHTTP2-6531285 (CVE-2023-45288) (CWE-770)
  go.mod
  go.sum
Labels: dependencies

#123 v3.1.4 release another vul fix
  go.mod
  go.sum
Labels: dependencies

#120 Create token DIR if not exists
  pkg/token/service.go
Labels: bug

#117 Treat IP Address as an optional parameter
  athenz-sia.env
  pkg/certificate/identity.go
  pkg/config/config.go
  pkg/config/default.go
Labels: bug, enhancement
