Repository AthenZ/k8s-athenz-sia, pull requests merged in 2025-03, with the labels that each got.

#187 remove duplicated package comments
  pkg/config/derived-k8s-secret-backup.go
  pkg/config/derived-role-cert.go
  pkg/config/derived-service-cert.go
  pkg/config/derived-target-domain-roles.go
  pkg/config/derived-token-file.go
  pkg/config/derived-token-server.go
  pkg/config/dervied.go
Labels: refactor

#188 fix github action issue in #182
  .github/workflows/docker-build-publish.yaml
Labels: dependencies

#185 New `CERT_SUBJECT` ENVs for customizing certificate subject
  Makefile
  athenz-sia.env
  go.mod
  go.sum
  pkg/certificate/identity.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/derived-cert-subject.go
  pkg/config/derived-cert-subject_test.go
  pkg/config/derived-role-cert.go
  pkg/config/derived-service-cert.go
  pkg/config/derived-service-cert_test.go
  pkg/config/dervied.go
  pkg/config/model.go
Labels: enhancement, dependencies

#190 bump: `github.com/golang-jwt/jwt/v5`: `5.2.1`=>`5.2.2`
  go.mod
  go.sum
Labels: dependencies
